name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    env:      
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: MySql Start
        run: |
          echo "running MYSQL from CLI"
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}      
          mysql -e 'SHOW TABLES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}      

      # - uses: ./action-a
      #   with:
      #     MY_NAME: "Mona"
